# Prenalysis to final df

From single_session_analysis.ipynb results of every session.

In [1]:
import pandas as pd
import os
import json
import numpy as np
from itertools import groupby
import matplotlib.pyplot as plt
from scipy import stats,signal
import matplotlib as mpl
from sklearn.linear_model import LogisticRegression
import random
import re
import csv
from IPython.display import HTML, display, Image
import tabulate
import math as m
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as sm
import statsmodels.formula.api as smf

mpl.rcParams['lines.linewidth'] = 3
mpl.rcParams['axes.titlesize'] = 18
mpl.rcParams['axes.labelsize'] = 18
mpl.rcParams['lines.markersize'] = 10
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20
mpl.rcParams['axes.linewidth'] = 3
#mpl.rcParams['xtick.major.size'] = 20
mpl.rcParams['xtick.major.width'] = 4
#mpl.rcParams['xtick.minor.size'] = 10
mpl.rcParams['xtick.minor.width'] = 2
mpl.rcParams['ytick.major.width'] = 4
mpl.rcParams['ytick.minor.width'] = 2

fday = [1,2,3,4,5,6,7,8,9,10]
fsession = [1,2]

In [ ]:
current_path = os.path.abspath(os.getcwd())
parent_path = os.path.abspath(os.path.join(current_path, os.pardir))
grand_parent_path = os.path.abspath(os.path.join(parent_path, os.pardir))
main_path = os.path.abspath(os.path.join(grand_parent_path, os.pardir))

path_results = main_path+'/results/gabor/'
path_data =

In [2]:
rep_list = []
for Day in fday:
    for Ses in fsession:
        path = '/home/cbclab/Documents/jatos_gabor_data/tanda1/day'+str(Day)+'/session'+str(Ses)+'/'
        data_files = [f for f in os.listdir(path) if f.endswith('_day'+str(Day)+'_session'+str(Ses))]
        # sort files
        subj_data = [int(re.search('%s(.*)%s' % ('', '_day'), f).group(1)) for f in data_files]
        sorted_subj_data = sorted(subj_data)
        index_subj_data = [subj_data.index(elem) for elem in sorted_subj_data]
        sorted_data_files = [data_files[i] for i in index_subj_data]
        # reports, staircase, deterministic and stochastic df for each participant
        Rdf = {}
        for name in sorted_subj_data: 
            Rdf[name] = {}
        ind = -1
        for ses in sorted_data_files:
            ind += 1
            #print(sorted_subj_data[ind])
            data = []
            for line in open(path+ses, 'r'):
                if line.strip():
                    data.append(json.loads(line))
            if Day==1 and Ses==1:
                reports = data[1]
            else:
                reports = data[0]
            part = reports['userID']
            if int(part)>1015 and int(part)<1201:
                part = str(int(part)-186)
            elif int(part)>1201:
                part = str(int(part)-217)

            if reports['sessionID']%2==0:
                session = 2
            else:
                session = 1
                
            Rdf[sorted_subj_data[ind]] = reports   
            del Rdf[sorted_subj_data[ind]]['date']
            rep_list.append(reports)

In [3]:
Rdf = pd.DataFrame(rep_list)

In [4]:
Rdf['userID'] = Rdf['userID'].astype(int)

In [5]:
# rename userID refered to the first deployment userID
secondIDs = [elem for elem in Rdf['userID'].unique() if elem>1015 and elem<1201]
thirdIDs = [elem for elem in Rdf['userID'].unique() if elem>1201]

for ids in secondIDs:
    Rdf.loc[Rdf.userID == ids, 'userID'] = ids-186
for ids in thirdIDs:
    Rdf.loc[Rdf.userID == ids, 'userID'] = ids-217

In [6]:
stress_list = list(Rdf['stress'])
real_stress = [1-elem for elem in stress_list]
Rdf['real_stress'] = real_stress

In [7]:
Rdf['sessionID'] = Rdf['sessionID'].astype(int)
Rdf['userID'] = Rdf['userID'].astype(int)

In [8]:
rep_userID = list(Rdf['userID'])
rep_sessionID = list(Rdf['sessionID'])
rep_user_sessionID = []
for i in range(len(rep_userID)):
    rep_user_sessionID.append(str(rep_userID[i])+'_'+str(rep_sessionID[i]))
Rdf['user_sessionID']=rep_user_sessionID

In [9]:
Rdf_sin_nan = Rdf

In [10]:
Rdf['sessionID'] = Rdf['sessionID'].astype(int)
Rdf['userID'] = Rdf['userID'].astype(int)

In [11]:
path_df = '/home/cbclab/Dropbox/postdocUPF/jatos_experiments/gabor/notebooks/results_tanda_1/across_sessions/'

data_files = [f for f in os.listdir(path_df) if f.startswith('average')]
df = {}
for f in data_files:
    data = [json.loads(line) for line in open(path_df+f, 'r')]
    df[data[0]['sessionID'][0]]=pd.DataFrame.from_dict(data[0])

DF = pd.concat([df[elem] for elem in range(1,len(data_files)+1)])

In [12]:
DF['sessionID'] = DF['sessionID'].astype(int)
DF['participantID'] = DF['participantID'].astype(int)

In [13]:
gabor_user_sessionID=[]
gabor_userID = list(DF['participantID'])
gabor_sessionID = list(DF['sessionID'])
for i in range(len(gabor_userID)):
    gabor_user_sessionID.append(str(gabor_userID[i])+'_'+str(gabor_sessionID[i]))
DF['user_sessionID']=gabor_user_sessionID

In [14]:
# rename userID refered to the first deployment userID
secondIDs = [elem for elem in DF['participantID'].unique() if elem>1015 and elem<1201]
thirdIDs = [elem for elem in DF['participantID'].unique() if elem>1201]
for ids in secondIDs:
    DF.loc[DF.userID == ids, 'participantID'] = ids-186
for ids in thirdIDs:
    DF.loc[DF.userID == ids, 'participantID'] = ids-217

In [15]:
adf = pd.merge(Rdf,DF,on='user_sessionID',how='outer')

In [16]:
df_Hopt = pd.DataFrame(columns=['user_sessionID','HRopt_','SO_HRopt'])
for Day in fday:
    for Ses in fsession:
        sessionid = 2*Day-2+Ses
        path = '/home/cbclab/Dropbox/postdocUPF/jatos_experiments/gabor/notebooks/results_tanda_1/day'+str(Day)+'/session'+str(Ses)+'/'
        optimalH_files = [f for f in os.listdir(path) if f.startswith('optimalH')]
        subj_optimalH = [int(re.search('%s(.*)%s' % ('optimalH_Sub', '_Day'), f).group(1)) for f in optimalH_files]
        sorted_subj_optimalH = sorted(subj_optimalH)
        index_subj_optimalH = [subj_optimalH.index(elem) for elem in sorted_subj_optimalH]
        sorted_optimalH_files = [optimalH_files[i] for i in index_subj_optimalH]
        for filename in sorted_optimalH_files:
            # optimalH
            f = filename
            filename=path+f
            with open(filename) as f:
                data = json.load(f)
            for k, v in data.items():
                globals()[k]=v
            df_Hopt = df_Hopt.append({'HRopt_': HRopt_,'SO_HRopt_': SO_HRopt_,"user_sessionID":part_sessid},ignore_index=True)

In [17]:
adf = pd.merge(adf,df_Hopt,on='user_sessionID',how='outer')

In [18]:
df_PCfit = pd.DataFrame()
for Day in fday:
    for Ses in fsession:
        sessionid = 2*Day-2+Ses
        path = '/home/cbclab/Dropbox/postdocUPF/jatos_experiments/gabor/notebooks/results_tanda_1/day'+str(Day)+'/session'+str(Ses)+'/'
        # Deterministic PC fit
        DOfit_files = [f for f in os.listdir(path) if f.startswith('DO_fit')]
        aux = [f.replace('DO_fit_oo_Sub','') for f in DOfit_files]
        subj_DOfit = [int(f.replace('_Day'+str(Day)+'_Sess'+str(Ses)+'.json','')) for f in aux]
        sorted_subj_DOfit = sorted(subj_DOfit)
        index_subj_DOfit = [subj_DOfit.index(elem) for elem in sorted_subj_DOfit]
        sorted_DOfit_files = [DOfit_files[i] for i in index_subj_DOfit]
        
        # NO PC fit
        NOfit_files = [f for f in os.listdir(path) if f.startswith('NO_fit')]
        auxNO = [f.replace('NO_fit_Sub','') for f in NOfit_files]
        subj_NOfit = [int(f.replace('_Day'+str(Day)+'_Sess'+str(Ses)+'.json','')) for f in auxNO]
        sorted_subj_NOfit = sorted(subj_NOfit)
        index_subj_NOfit = [subj_NOfit.index(elem) for elem in sorted_subj_NOfit]
        sorted_NOfit_files = [NOfit_files[i] for i in index_subj_NOfit]
        
        # Stochastic PC fit
        SOfit_files = [f for f in os.listdir(path) if f.startswith('SO_fit')]
        auxSO = [f.replace('SO_fit_oo_Sub','') for f in SOfit_files]
        subj_SOfit = [int(f.replace('_Day'+str(Day)+'_Sess'+str(Ses)+'.json','')) for f in auxSO]
        sorted_subj_SOfit = sorted(subj_SOfit)
        index_subj_SOfit = [subj_SOfit.index(elem) for elem in sorted_subj_SOfit]
        sorted_SOfit_files = [SOfit_files[i] for i in index_subj_SOfit]
        
        ind = -1
        for filename in sorted_DOfit_files:
            ind += 1
            partid = sorted_subj_DOfit[ind]
            part_sessid = str(partid)+'_'+str(sessionid)
            # deterministic PC fit
            f = filename
            filename=path+f
            with open(filename) as f:
                data = json.load(f)
            for k, v in data.items():
                globals()[k]=v
                
            # psychometric curve NON-optout
            fNO = sorted_NOfit_files[ind]
            filename=path+fNO
            with open(filename) as fNO:
                dataNO = json.load(fNO)
            for k, v in dataNO.items():
                globals()[k]=v     
                
            # stochastic PC fit
            fSO = sorted_SOfit_files[ind]
            filename=path+fSO
            with open(filename) as fSO:
                dataSO = json.load(fSO)
            for k, v in dataSO.items():
                globals()[k]=v   
                
            df_PCfit = df_PCfit.append({'DHR_oo': DHR_oo,'DHL_oo':DHL_oo,'Dsigma_oo':Dsigma_oo,\
                                        'SHR_oo': SHR_oo,'SHL_oo':SHL_oo,'Ssigma_oo':Ssigma_oo,\
                                        'no_sigma':Sigma, 'no_bias':Hno,\
                                        "user_sessionID":part_sessid},ignore_index=True)

In [19]:
df_PCfit['HmiddleDO']=(df_PCfit['DHR_oo']+df_PCfit['DHL_oo'])/2
df_PCfit['HmiddleSO']=(df_PCfit['SHR_oo']+df_PCfit['SHL_oo'])/2

In [20]:
adf = pd.merge(adf,df_PCfit,on='user_sessionID',how='outer')

In [21]:
adf['risk_av'] = (adf['Dsubj_perf_oo']-adf['Ssubj_perf_oo'])/100.0

In [22]:
adf['DoverConf'] = (np.abs(2*adf['HRopt_'])-np.abs(adf['DHL_oo']-adf['DHR_oo']))/(np.abs(2*adf['HRopt_'])+np.abs(adf['DHL_oo']-adf['DHR_oo']))

In [23]:
adf['SoverConf'] = (np.abs(2*adf['SO_HRopt_'])-np.abs(adf['SHL_oo']-adf['SHR_oo']))/(np.abs(2*adf['SO_HRopt_'])+np.abs(adf['SHL_oo']-adf['SHR_oo']))

In [24]:
# miss a session

excluded_miss = ['1011_11', '1011_18', '1014_12']
adf = adf[~adf['user_sessionID'].isin(excluded_miss)]

In [25]:
adf_column_names = list(adf.columns)

column_names = [x for x in adf_column_names if x not in ['sessionID_x','sessionID_y','userID','userID_y',\
                                                         'participantID','user_sessionID']]

nan_dict = {}
for i in column_names:
    nan_dict[i] = np.nan

replace = [{'sessionID_x':int(elem.split('_')[1]),'sessionID_y':int(elem.split('_')[1]), \
             'userID':int(elem.split('_')[0]), 'userID_y':int(elem.split('_')[0]),\
            'participantID':int(elem.split('_')[0]),'user_sessionID':elem} for elem in excluded_miss]

for i in range(len(replace)):
    replace[i].update(nan_dict)
    
for elem in replace:
    adf = adf.append(elem, ignore_index=True)

In [26]:
# exclude 2 sessions because the meedian RT for some difficulties was greater than 2 s

excluded_time = ['1008_2','1009_9']

In [27]:
# adf = adf[~adf['user_sessionID'].isin(excluded)]

In [28]:
adf_column_names = list(adf.columns)

column_names = [x for x in adf_column_names if x not in ['userID','sessionID_x','sessionID_y','userID_x','userID_y',\
                                                         'participantID','user_sessionID']]

for ex in excluded_time:
    for col in column_names:
        adf.loc[adf.user_sessionID == ex, col] = np.nan

In [29]:
adf.groupby(['userID']).size()

userID
991     20
992     20
993     20
994     20
995     20
996     20
997     20
998     20
999     20
1000    20
1001    20
1002    20
1003    20
1005    20
1006    20
1007    20
1008    20
1009    20
1010    20
1011    20
1012    20
1013    20
1014    20
dtype: int64

In [30]:
adf[adf['userID']==1011]

,mood,sleep,food,stress,sessionID_x,userID,real_stress,user_sessionID,participantID,sessionID_y,...,SHR_oo,Ssigma_oo,no_bias,no_sigma,HmiddleDO,HmiddleSO,risk_av,DoverConf,SoverConf,userID_y
19,0.70,0.34,0.63,0.53,1,1011,0.47,1011_1,1011,1,...,0.571903,0.733452,-0.042814,1.007085,-0.057207,-0.207316,-0.006614,0.755658,0.781330,NaN
42,0.69,NaN,0.70,0.57,2,1011,0.43,1011_2,1011,2,...,0.524009,0.622040,-0.042604,0.158179,0.072891,-0.058113,-0.094444,-0.446682,-0.445910,NaN
65,0.58,0.68,0.87,0.51,3,1011,0.49,1011_3,1011,3,...,0.343302,0.510067,-0.089412,0.396936,-0.090246,-0.116993,-0.171673,0.052352,0.374077,NaN
88,0.58,NaN,0.67,0.74,4,1011,0.26,1011_4,1011,4,...,0.967029,0.981903,0.286480,0.955512,0.053568,0.113278,-0.049603,0.757189,0.726739,NaN
111,0.69,0.94,0.64,0.69,5,1011,0.31,1011_5,1011,5,...,0.290835,0.628296,0.041240,0.225226,0.197505,-0.212718,-0.144444,-0.404028,-0.138485,NaN
134,0.40,NaN,0.58,0.32,6,1011,0.68,1011_6,1011,6,...,0.018218,0.543218,0.000000,0.000010,-0.024678,-0.005593,0.000000,-0.003014,0.615358,NaN
157,0.86,0.86,0.60,0.85,7,1011,0.15,1011_7,1011,7,...,0.485815,0.539835,-0.023106,0.256632,0.088105,0.038959,-0.196581,0.311793,0.015645,NaN
180,0.76,NaN,0.92,0.82,8,1011,0.18,1011_8,1011,8,...,0.473758,0.607475,0.034123,0.804572,-0.014493,-0.075027,-0.071098,0.799598,0.785878,NaN
203,0.26,0.49,0.56,0.33,9,1011,0.67,1011_9,1011,9,...,0.573461,0.598852,-0.015703,0.148083,0.326618,0.095278,-0.071429,-0.664518,-0.367854,NaN
226,0.51,NaN,0.48,0.49,10,1011,0.51,1011_10,1011,10,...,0.609176,0.588946,0.051956,0.139286,0.080104,0.028849,0.147090,-0.729029,-0.624877,NaN
271,0.92,NaN,0.68,0.88,12,1011,0.12,1011_12,1011,12,...,0.458214,0.620902,-0.007972,0.195372,0.079130,-0.129643,0.166667,-0.254492,-0.312204,NaN
293,0.73,0.75,0.76,0.78,13,1011,0.22,1011_13,1011,13,...,0.017918,0.119519,-0.012572,0.269620,-0.015526,-0.055204,0.058201,0.556439,0.782423,NaN
316,0.78,NaN,0.78,0.78,14,1011,0.22,1011_14,1011,14,...,0.341593,0.513972,-0.019193,0.127398,-0.063589,0.067160,-0.002037,-0.426140,-0.277858,NaN
339,1.00,0.97,0.67,1.00,15,1011,0.00,1011_15,1011,15,...,0.280171,0.510239,0.070854,0.152062,0.123654,-0.046384,0.150000,-0.844877,-0.517372,NaN
362,0.71,NaN,0.62,0.73,16,1011,0.27,1011_16,1011,16,...,0.466931,0.542189,0.019261,0.183617,0.135237,0.150326,-0.036114,-0.359824,-0.195543,NaN
385,0.74,0.96,0.52,0.84,17,1011,0.16,1011_17,1011,17,...,0.065258,0.121803,0.012810,0.269188,0.028510,-0.006584,-0.103739,0.319386,0.709873,NaN
430,0.77,0.92,0.62,0.56,19,1011,0.44,1011_19,1011,19,...,0.424470,0.506858,0.075260,0.230328,0.021985,0.004096,-0.015640,-0.350024,-0.236646,NaN
453,1.00,NaN,1.00,1.00,20,1011,0.00,1011_20,1011,20,...,0.294626,0.516400,0.123538,0.274776,0.296925,-0.109264,-0.039433,-0.480904,-0.102948,NaN
457,NaN,NaN,NaN,NaN,11,1011,NaN,1011_11,1011,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1011.0
458,NaN,NaN,NaN,NaN,18,1011,NaN,1011_18,1011,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1011.0

In [31]:
adf.head()

,mood,sleep,food,stress,sessionID_x,userID,real_stress,user_sessionID,participantID,sessionID_y,...,SHR_oo,Ssigma_oo,no_bias,no_sigma,HmiddleDO,HmiddleSO,risk_av,DoverConf,SoverConf,userID_y
0,0.52,0.33,0.51,0.63,1,991,0.37,991_1,991,1,...,0.494928,0.539028,-0.063783,0.223975,-0.106358,0.038783,0.125397,-0.559279,-0.126271,NaN
1,1.00,0.73,0.50,0.31,1,992,0.69,992_1,992,1,...,0.506537,0.558062,0.060239,0.219475,0.225197,0.201023,-0.163355,-0.259551,0.057653,NaN
2,0.62,0.63,0.85,0.26,1,993,0.74,993_1,993,1,...,0.738446,0.731049,-0.066321,0.520330,-0.116809,0.298085,0.031777,0.687934,0.657011,NaN
3,1.00,0.72,0.53,0.36,1,994,0.64,994_1,994,1,...,0.138399,0.504628,0.011453,0.200953,0.017636,-0.122779,0.029101,-0.406121,-0.041423,NaN
4,0.66,0.28,0.08,1.00,1,995,0.00,995_1,995,1,...,0.004459,0.759882,-0.275513,0.174552,-0.210000,-0.265184,-0.112745,1.000000,-0.458925,NaN

In [32]:
adf = adf.sort_values(by = ['userID', 'sessionID_y'])

In [33]:
adf['real_OK_NO_RT'] = adf['OKubj_RT_no']*adf['medianRT']
adf['real_OK_DO_RT'] = adf['OKDsubj_RT_oo']*adf['medianRT']
adf['real_OK_SO_RT'] = adf['OKSsubj_RT_oo']*adf['medianRT']
adf['real_NOK_NO_RT'] = adf['NOKubj_RT_no']*adf['medianRT']
adf['real_DO_RT'] = adf['Dsubj_RT_oo']*adf['medianRT']
adf['real_SO_RT'] = adf['Ssubj_RT_oo']*adf['medianRT']

In [34]:
adf['sessionID_x'] = adf['sessionID_x'].astype(int)
adf['userID'] = adf['userID'].astype('Int64')

In [35]:
adf[adf['userID']==1011]

,mood,sleep,food,stress,sessionID_x,userID,real_stress,user_sessionID,participantID,sessionID_y,...,risk_av,DoverConf,SoverConf,userID_y,real_OK_NO_RT,real_OK_DO_RT,real_OK_SO_RT,real_NOK_NO_RT,real_DO_RT,real_SO_RT
19,0.70,0.34,0.63,0.53,1,1011,0.47,1011_1,1011,1,...,-0.006614,0.755658,0.781330,NaN,1318.8200,1006.6900,1026.1400,1332.9800,1193.1150,1244.5150
42,0.69,NaN,0.70,0.57,2,1011,0.43,1011_2,1011,2,...,-0.094444,-0.446682,-0.445910,NaN,976.2275,875.1550,898.6200,1228.0450,958.4000,941.5575
65,0.58,0.68,0.87,0.51,3,1011,0.49,1011_3,1011,3,...,-0.171673,0.052352,0.374077,NaN,1091.2850,851.2100,957.5800,1073.6750,958.0550,919.9975
88,0.58,NaN,0.67,0.74,4,1011,0.26,1011_4,1011,4,...,-0.049603,0.757189,0.726739,NaN,856.3750,843.7300,854.4900,955.2750,894.0675,870.6100
111,0.69,0.94,0.64,0.69,5,1011,0.31,1011_5,1011,5,...,-0.144444,-0.404028,-0.138485,NaN,937.8850,825.0250,831.8075,1137.0350,976.0825,931.3600
134,0.40,NaN,0.58,0.32,6,1011,0.68,1011_6,1011,6,...,0.000000,-0.003014,0.615358,NaN,760.9400,782.4900,769.0225,NaN,914.7000,787.0650
157,0.86,0.86,0.60,0.85,7,1011,0.15,1011_7,1011,7,...,-0.196581,0.311793,0.015645,NaN,870.6800,793.0300,853.3350,1153.2775,846.7900,836.7550
180,0.76,NaN,0.92,0.82,8,1011,0.18,1011_8,1011,8,...,-0.071098,0.799598,0.785878,NaN,854.1400,796.9500,861.1550,853.3700,867.5550,795.3350
203,0.26,0.49,0.56,0.33,9,1011,0.67,1011_9,1011,9,...,-0.071429,-0.664518,-0.367854,NaN,823.5100,853.8650,815.8400,866.5600,841.6050,841.4450
226,0.51,NaN,0.48,0.49,10,1011,0.51,1011_10,1011,10,...,0.147090,-0.729029,-0.624877,NaN,798.0250,775.4200,838.8575,831.3900,851.0125,826.0275
457,NaN,NaN,NaN,NaN,11,1011,NaN,1011_11,1011,11,...,NaN,NaN,NaN,1011.0,NaN,NaN,NaN,NaN,NaN,NaN
271,0.92,NaN,0.68,0.88,12,1011,0.12,1011_12,1011,12,...,0.166667,-0.254492,-0.312204,NaN,788.6175,783.9400,779.6825,801.2050,775.2200,806.6100
293,0.73,0.75,0.76,0.78,13,1011,0.22,1011_13,1011,13,...,0.058201,0.556439,0.782423,NaN,794.6100,763.0300,771.3825,924.4050,851.1350,817.8550
316,0.78,NaN,0.78,0.78,14,1011,0.22,1011_14,1011,14,...,-0.002037,-0.426140,-0.277858,NaN,815.8900,765.5975,784.8700,1077.7650,935.3500,862.6800
339,1.00,0.97,0.67,1.00,15,1011,0.00,1011_15,1011,15,...,0.150000,-0.844877,-0.517372,NaN,783.9650,784.7300,802.0850,818.7700,878.6900,839.8050
362,0.71,NaN,0.62,0.73,16,1011,0.27,1011_16,1011,16,...,-0.036114,-0.359824,-0.195543,NaN,831.5100,860.0850,834.7900,968.3600,903.6700,996.9350
385,0.74,0.96,0.52,0.84,17,1011,0.16,1011_17,1011,17,...,-0.103739,0.319386,0.709873,NaN,791.7500,769.0100,787.1675,902.4650,870.1050,842.2450
458,NaN,NaN,NaN,NaN,18,1011,NaN,1011_18,1011,18,...,NaN,NaN,NaN,1011.0,NaN,NaN,NaN,NaN,NaN,NaN
430,0.77,0.92,0.62,0.56,19,1011,0.44,1011_19,1011,19,...,-0.015640,-0.350024,-0.236646,NaN,744.4600,733.4950,745.2950,806.3475,698.6250,852.6700
453,1.00,NaN,1.00,1.00,20,1011,0.00,1011_20,1011,20,...,-0.039433,-0.480904,-0.102948,NaN,957.2200,711.7100,913.9450,1072.7800,1210.0775,1073.8150

In [36]:
adf.to_csv('preanalyzed.csv',index=False)

In [ ]:
len(adf)